window.statementParser = /*
 * Generated by PEG.js 0.10.0.
 *
 * http://pegjs.org/
 */
(function() {
  "use strict";

  function peg$subclass(child, parent) {
    function ctor() { this.constructor = child; }
    ctor.prototype = parent.prototype;
    child.prototype = new ctor();
  }

  function peg$SyntaxError(message, expected, found, location) {
    this.message  = message;
    this.expected = expected;
    this.found    = found;
    this.location = location;
    this.name     = "SyntaxError";

    if (typeof Error.captureStackTrace === "function") {
      Error.captureStackTrace(this, peg$SyntaxError);
    }
  }

  peg$subclass(peg$SyntaxError, Error);

  peg$SyntaxError.buildMessage = function(expected, found) {
    var DESCRIBE_EXPECTATION_FNS = {
          literal: function(expectation) {
            return "\"" + literalEscape(expectation.text) + "\"";
          },

          "class": function(expectation) {
            var escapedParts = "",
                i;

            for (i = 0; i < expectation.parts.length; i++) {
              escapedParts += expectation.parts[i] instanceof Array
                ? classEscape(expectation.parts[i][0]) + "-" + classEscape(expectation.parts[i][1])
                : classEscape(expectation.parts[i]);
            }

            return "[" + (expectation.inverted ? "^" : "") + escapedParts + "]";
          },

          any: function(expectation) {
            return "any character";
          },

          end: function(expectation) {
            return "end of input";
          },

          other: function(expectation) {
            return expectation.description;
          }
        };

    function hex(ch) {
      return ch.charCodeAt(0).toString(16).toUpperCase();
    }

    function literalEscape(s) {
      return s
        .replace(/\\/g, '\\\\')
        .replace(/"/g,  '\\"')
        .replace(/\0/g, '\\0')
        .replace(/\t/g, '\\t')
        .replace(/\n/g, '\\n')
        .replace(/\r/g, '\\r')
        .replace(/[\x00-\x0F]/g,          function(ch) { return '\\x0' + hex(ch); })
        .replace(/[\x10-\x1F\x7F-\x9F]/g, function(ch) { return '\\x'  + hex(ch); });
    }

    function classEscape(s) {
      return s
        .replace(/\\/g, '\\\\')
        .replace(/\]/g, '\\]')
        .replace(/\^/g, '\\^')
        .replace(/-/g,  '\\-')
        .replace(/\0/g, '\\0')
        .replace(/\t/g, '\\t')
        .replace(/\n/g, '\\n')
        .replace(/\r/g, '\\r')
        .replace(/[\x00-\x0F]/g,          function(ch) { return '\\x0' + hex(ch); })
        .replace(/[\x10-\x1F\x7F-\x9F]/g, function(ch) { return '\\x'  + hex(ch); });
    }

    function describeExpectation(expectation) {
      return DESCRIBE_EXPECTATION_FNS[expectation.type](expectation);
    }

    function describeExpected(expected) {
      var descriptions = new Array(expected.length),
          i, j;

      for (i = 0; i < expected.length; i++) {
        descriptions[i] = describeExpectation(expected[i]);
      }

      descriptions.sort();

      if (descriptions.length > 0) {
        for (i = 1, j = 1; i < descriptions.length; i++) {
          if (descriptions[i - 1] !== descriptions[i]) {
            descriptions[j] = descriptions[i];
            j++;
          }
        }
        descriptions.length = j;
      }

      switch (descriptions.length) {
        case 1:
          return descriptions[0];

        case 2:
          return descriptions[0] + " or " + descriptions[1];

        default:
          return descriptions.slice(0, -1).join(", ")
            + ", or "
            + descriptions[descriptions.length - 1];
      }
    }

    function describeFound(found) {
      return found ? "\"" + literalEscape(found) + "\"" : "end of input";
    }

    return "Expected " + describeExpected(expected) + " but " + describeFound(found) + " found.";
  };

  function peg$parse(input, options) {
    options = options !== void 0 ? options : {};

    var peg$FAILED = {},

        peg$startRuleIndices = { Statement: 0 },
        peg$startRuleIndex   = 0,

        peg$consts = [
          " if ",
          peg$literalExpectation(" if ", false),
          function(statementHead, conditions) { return ["if",statementHead,conditions] },
          "causes1way",
          peg$literalExpectation("causes1way", false),
          "causes2way",
          peg$literalExpectation("causes2way", false),
          function(cause, causeType, effect) { return [causeType,cause,effect] },
          "not",
          peg$literalExpectation("not", false),
          "(",
          peg$literalExpectation("(", false),
          ")",
          peg$literalExpectation(")", false),
          "link",
          peg$literalExpectation("link", false),
          "influence",
          peg$literalExpectation("influence", false),
          "comparison",
          peg$literalExpectation("comparison", false),
          " and ",
          peg$literalExpectation(" and ", false),
          " or ",
          peg$literalExpectation(" or ", false),
          "att_value(",
          peg$literalExpectation("att_value(", false),
          ",",
          peg$literalExpectation(",", false),
          function(object, attribute, value) {return ['att_value',object,attribute,value]},
          function(process, attribute, value) {return ['att_value',process,attribute,value]},
          "att_value(action(",
          peg$literalExpectation("att_value(action(", false),
          "action(",
          peg$literalExpectation("action(", false),
          function(action, object1, object2) { ['action',action,object1,object2]},
          function(action, object1) { return ['action',action,object1] },
          "process",
          peg$literalExpectation("process", false),
          function(attribute) {return attribute},
          "part(",
          peg$literalExpectation("part(", false),
          function(object1, object2) { return ["part",object1,object2]; },
          "greater_than",
          peg$literalExpectation("greater_than", false),
          "less_than",
          peg$literalExpectation("less_than", false),
          "same_as",
          peg$literalExpectation("same_as", false),
          "different_from",
          peg$literalExpectation("different_from", false),
          "increase",
          peg$literalExpectation("increase", false),
          "decrease",
          peg$literalExpectation("decrease", false),
          "change",
          peg$literalExpectation("change", false),
          "no_change",
          peg$literalExpectation("no_change", false),
          "range",
          peg$literalExpectation("range", false),
          /^[a-zA-Z_]/,
          peg$classExpectation([["a", "z"], ["A", "Z"], "_"], false, false),
          function(letters) {return letters.join("")},
          /^[0-9]/,
          peg$classExpectation([["0", "9"]], false, false),
          /^[ \t\n\r]/,
          peg$classExpectation([" ", "\t", "\n", "\r"], false, false),
          function() {return null}
        ],

        peg$bytecode = [
          peg$decode("%;!/A#2 \"\"6 7!/2$;\"/)$8#:\"#\"\" )(#'#(\"'#&'#.# &;!"),
          peg$decode("%;%/`#;0/W$2#\"\"6#7$.) &2%\"\"6%7&/<$;0/3$;'/*$8%:'%#$\" )(%'#($'#(#'#(\"'#&'#.\u025D &;$.\u0257 &%2(\"\"6(7)/J#2*\"\"6*7+/;$;$/2$2,\"\"6,7-/#$+$)($'#(#'#(\"'#&'#.\u021A &%2.\"\"6.7//t#2*\"\"6*7+/e$20\"\"6071/V$;1/M$;)/D$;1/;$;)/2$2,\"\"6,7-/#$+()(('#(''#(&'#(%'#($'#(#'#(\"'#&'#.\u01B3 &%2.\"\"6.7//n#2*\"\"6*7+/_$;./V$;1/M$;+/D$;1/;$;+/2$2,\"\"6,7-/#$+()(('#(''#(&'#(%'#($'#(#'#(\"'#&'#.\u0152 &%2.\"\"6.7//n#2*\"\"6*7+/_$;./V$;1/M$;(/D$;1/;$;(/2$2,\"\"6,7-/#$+()(('#(''#(&'#(%'#($'#(#'#(\"'#&'#.\xF1 &%2.\"\"6.7//n#2*\"\"6*7+/_$;./V$;1/M$;(/D$;1/;$;+/2$2,\"\"6,7-/#$+()(('#(''#(&'#(%'#($'#(#'#(\"'#&'#.\x90 &%22\"\"6273/\x80#2*\"\"6*7+/q$;*/h$;1/_$;+/V$;1/M$;,/D$;1/;$;+/2$2,\"\"6,7-/#$+*)(*'#()'#(('#(''#(&'#(%'#($'#(#'#(\"'#&'#"),
          peg$decode("%;#/;#24\"\"6475/,$;#/#$+#)(#'#(\"'#&'#.K &%;#/;#26\"\"6677/,$;#/#$+#)(#'#(\"'#&'#.# &;#"),
          peg$decode(";&.) &;!.# &;("),
          peg$decode("%28\"\"6879/c#;+/Z$2:\"\"6:7;/K$;*/B$;-/9$2,\"\"6,7-/*$8&:<&#$\"!)(&'#(%'#($'#(#'#(\"'#&'#.\xD4 &%28\"\"6879/r#;(/i$2:\"\"6:7;/Z$;*/Q$2:\"\"6:7;/B$;-/9$2,\"\"6,7-/*$8':='#%#!)(''#(&'#(%'#($'#(#'#(\"'#&'#.o &%2>\"\"6>7?/_#;&/V$;1/M$;*/D$;1/;$;-/2$2,\"\"6,7-/#$+')(''#(&'#(%'#($'#(#'#(\"'#&'#"),
          peg$decode(";$.l &;(.f &;&.` &;+.Z &%2(\"\"6(7)/J#2*\"\"6*7+/;$;%/2$2,\"\"6,7-/#$+$)($'#(#'#(\"'#&'#"),
          peg$decode("%2@\"\"6@7A/T#;./K$;+/B$;+/9$2,\"\"6,7-/*$8%:B%##\"!)(%'#($'#(#'#(\"'#&'#.i &%2@\"\"6@7A/Y#;./P$2:\"\"6:7;/A$;+/8$2,\"\"6,7-/)$8%:C%\"#!)(%'#($'#(#'#(\"'#&'#"),
          peg$decode(";$.f &;(.` &;&.Z &%2(\"\"6(7)/J#2*\"\"6*7+/;$;'/2$2,\"\"6,7-/#$+$)($'#(#'#(\"'#&'#"),
          peg$decode("%2D\"\"6D7E/J#2*\"\"6*7+/;$;./2$2,\"\"6,7-/#$+$)($'#(#'#(\"'#&'#.\xCD &%2D\"\"6D7E/\\#2*\"\"6*7+/M$;+/D$;1/;$;./2$2,\"\"6,7-/#$+&)(&'#(%'#($'#(#'#(\"'#&'#.~ &%2D\"\"6D7E/n#2*\"\"6*7+/_$;+/V$;1/M$;./D$;1/;$;+/2$2,\"\"6,7-/#$+()(('#(''#(&'#(%'#($'#(#'#(\"'#&'#"),
          peg$decode(";+.# &;("),
          peg$decode("%;./7#2:\"\"6:7;/($8\":F\"!!)(\"'#&'#"),
          peg$decode("%2G\"\"6G7H/Y#;./P$2:\"\"6:7;/A$;./8$2,\"\"6,7-/)$8%:I%\"#!)(%'#($'#(#'#(\"'#&'#.# &;."),
          peg$decode("2J\"\"6J7K.A &2L\"\"6L7M.5 &2N\"\"6N7O.) &2P\"\"6P7Q"),
          peg$decode("2R\"\"6R7S.A &2T\"\"6T7U.5 &2V\"\"6V7W.) &2X\"\"6X7Y.~ &;..x &;/.r &%2Z\"\"6Z7[/b#2*\"\"6*7+/S$;-/J$2:\"\"6:7;/;$;-/2$2,\"\"6,7-/#$+&)(&'#(%'#($'#(#'#(\"'#&'#"),
          peg$decode("%$4\\\"\"5!7]0)*4\\\"\"5!7]&/' 8!:^!! )"),
          peg$decode("$4_\"\"5!7`0)*4_\"\"5!7`&"),
          peg$decode("$4a\"\"5!7b0)*4a\"\"5!7b&"),
          peg$decode("%2:\"\"6:7;/0#;0/'$8\":c\" )(\"'#&'#")
        ],

        peg$currPos          = 0,
        peg$savedPos         = 0,
        peg$posDetailsCache  = [{ line: 1, column: 1 }],
        peg$maxFailPos       = 0,
        peg$maxFailExpected  = [],
        peg$silentFails      = 0,

        peg$result;

    if ("startRule" in options) {
      if (!(options.startRule in peg$startRuleIndices)) {
        throw new Error("Can't start parsing from rule \"" + options.startRule + "\".");
      }

      peg$startRuleIndex = peg$startRuleIndices[options.startRule];
    }

    function text() {
      return input.substring(peg$savedPos, peg$currPos);
    }

    function location() {
      return peg$computeLocation(peg$savedPos, peg$currPos);
    }

    function expected(description, location) {
      location = location !== void 0 ? location : peg$computeLocation(peg$savedPos, peg$currPos)

      throw peg$buildStructuredError(
        [peg$otherExpectation(description)],
        input.substring(peg$savedPos, peg$currPos),
        location
      );
    }

    function error(message, location) {
      location = location !== void 0 ? location : peg$computeLocation(peg$savedPos, peg$currPos)

      throw peg$buildSimpleError(message, location);
    }

    function peg$literalExpectation(text, ignoreCase) {
      return { type: "literal", text: text, ignoreCase: ignoreCase };
    }

    function peg$classExpectation(parts, inverted, ignoreCase) {
      return { type: "class", parts: parts, inverted: inverted, ignoreCase: ignoreCase };
    }

    function peg$anyExpectation() {
      return { type: "any" };
    }

    function peg$endExpectation() {
      return { type: "end" };
    }

    function peg$otherExpectation(description) {
      return { type: "other", description: description };
    }

    function peg$computePosDetails(pos) {
      var details = peg$posDetailsCache[pos], p;

      if (details) {
        return details;
      } else {
        p = pos - 1;
        while (!peg$posDetailsCache[p]) {
          p--;
        }

        details = peg$posDetailsCache[p];
        details = {
          line:   details.line,
          column: details.column
        };

        while (p < pos) {
          if (input.charCodeAt(p) === 10) {
            details.line++;
            details.column = 1;
          } else {
            details.column++;
          }

          p++;
        }

        peg$posDetailsCache[pos] = details;
        return details;
      }
    }

    function peg$computeLocation(startPos, endPos) {
      var startPosDetails = peg$computePosDetails(startPos),
          endPosDetails   = peg$computePosDetails(endPos);

      return {
        start: {
          offset: startPos,
          line:   startPosDetails.line,
          column: startPosDetails.column
        },
        end: {
          offset: endPos,
          line:   endPosDetails.line,
          column: endPosDetails.column
        }
      };
    }

    function peg$fail(expected) {
      if (peg$currPos < peg$maxFailPos) { return; }

      if (peg$currPos > peg$maxFailPos) {
        peg$maxFailPos = peg$currPos;
        peg$maxFailExpected = [];
      }

      peg$maxFailExpected.push(expected);
    }

    function peg$buildSimpleError(message, location) {
      return new peg$SyntaxError(message, null, null, location);
    }

    function peg$buildStructuredError(expected, found, location) {
      return new peg$SyntaxError(
        peg$SyntaxError.buildMessage(expected, found),
        expected,
        found,
        location
      );
    }

    function peg$decode(s) {
      var bc = new Array(s.length), i;

      for (i = 0; i < s.length; i++) {
        bc[i] = s.charCodeAt(i) - 32;
      }

      return bc;
    }

    function peg$parseRule(index) {
      var bc    = peg$bytecode[index],
          ip    = 0,
          ips   = [],
          end   = bc.length,
          ends  = [],
          stack = [],
          params, i;

      while (true) {
        while (ip < end) {
          switch (bc[ip]) {
            case 0:
              stack.push(peg$consts[bc[ip + 1]]);
              ip += 2;
              break;

            case 1:
              stack.push(void 0);
              ip++;
              break;

            case 2:
              stack.push(null);
              ip++;
              break;

            case 3:
              stack.push(peg$FAILED);
              ip++;
              break;

            case 4:
              stack.push([]);
              ip++;
              break;

            case 5:
              stack.push(peg$currPos);
              ip++;
              break;

            case 6:
              stack.pop();
              ip++;
              break;

            case 7:
              peg$currPos = stack.pop();
              ip++;
              break;

            case 8:
              stack.length -= bc[ip + 1];
              ip += 2;
              break;

            case 9:
              stack.splice(-2, 1);
              ip++;
              break;

            case 10:
              stack[stack.length - 2].push(stack.pop());
              ip++;
              break;

            case 11:
              stack.push(stack.splice(stack.length - bc[ip + 1], bc[ip + 1]));
              ip += 2;
              break;

            case 12:
              stack.push(input.substring(stack.pop(), peg$currPos));
              ip++;
              break;

            case 13:
              ends.push(end);
              ips.push(ip + 3 + bc[ip + 1] + bc[ip + 2]);

              if (stack[stack.length - 1]) {
                end = ip + 3 + bc[ip + 1];
                ip += 3;
              } else {
                end = ip + 3 + bc[ip + 1] + bc[ip + 2];
                ip += 3 + bc[ip + 1];
              }

              break;

            case 14:
              ends.push(end);
              ips.push(ip + 3 + bc[ip + 1] + bc[ip + 2]);

              if (stack[stack.length - 1] === peg$FAILED) {
                end = ip + 3 + bc[ip + 1];
                ip += 3;
              } else {
                end = ip + 3 + bc[ip + 1] + bc[ip + 2];
                ip += 3 + bc[ip + 1];
              }

              break;

            case 15:
              ends.push(end);
              ips.push(ip + 3 + bc[ip + 1] + bc[ip + 2]);

              if (stack[stack.length - 1] !== peg$FAILED) {
                end = ip + 3 + bc[ip + 1];
                ip += 3;
              } else {
                end = ip + 3 + bc[ip + 1] + bc[ip + 2];
                ip += 3 + bc[ip + 1];
              }

              break;

            case 16:
              if (stack[stack.length - 1] !== peg$FAILED) {
                ends.push(end);
                ips.push(ip);

                end = ip + 2 + bc[ip + 1];
                ip += 2;
              } else {
                ip += 2 + bc[ip + 1];
              }

              break;

            case 17:
              ends.push(end);
              ips.push(ip + 3 + bc[ip + 1] + bc[ip + 2]);

              if (input.length > peg$currPos) {
                end = ip + 3 + bc[ip + 1];
                ip += 3;
              } else {
                end = ip + 3 + bc[ip + 1] + bc[ip + 2];
                ip += 3 + bc[ip + 1];
              }

              break;

            case 18:
              ends.push(end);
              ips.push(ip + 4 + bc[ip + 2] + bc[ip + 3]);

              if (input.substr(peg$currPos, peg$consts[bc[ip + 1]].length) === peg$consts[bc[ip + 1]]) {
                end = ip + 4 + bc[ip + 2];
                ip += 4;
              } else {
                end = ip + 4 + bc[ip + 2] + bc[ip + 3];
                ip += 4 + bc[ip + 2];
              }

              break;

            case 19:
              ends.push(end);
              ips.push(ip + 4 + bc[ip + 2] + bc[ip + 3]);

              if (input.substr(peg$currPos, peg$consts[bc[ip + 1]].length).toLowerCase() === peg$consts[bc[ip + 1]]) {
                end = ip + 4 + bc[ip + 2];
                ip += 4;
              } else {
                end = ip + 4 + bc[ip + 2] + bc[ip + 3];
                ip += 4 + bc[ip + 2];
              }

              break;

            case 20:
              ends.push(end);
              ips.push(ip + 4 + bc[ip + 2] + bc[ip + 3]);

              if (peg$consts[bc[ip + 1]].test(input.charAt(peg$currPos))) {
                end = ip + 4 + bc[ip + 2];
                ip += 4;
              } else {
                end = ip + 4 + bc[ip + 2] + bc[ip + 3];
                ip += 4 + bc[ip + 2];
              }

              break;

            case 21:
              stack.push(input.substr(peg$currPos, bc[ip + 1]));
              peg$currPos += bc[ip + 1];
              ip += 2;
              break;

            case 22:
              stack.push(peg$consts[bc[ip + 1]]);
              peg$currPos += peg$consts[bc[ip + 1]].length;
              ip += 2;
              break;

            case 23:
              stack.push(peg$FAILED);
              if (peg$silentFails === 0) {
                peg$fail(peg$consts[bc[ip + 1]]);
              }
              ip += 2;
              break;

            case 24:
              peg$savedPos = stack[stack.length - 1 - bc[ip + 1]];
              ip += 2;
              break;

            case 25:
              peg$savedPos = peg$currPos;
              ip++;
              break;

            case 26:
              params = bc.slice(ip + 4, ip + 4 + bc[ip + 3]);
              for (i = 0; i < bc[ip + 3]; i++) {
                params[i] = stack[stack.length - 1 - params[i]];
              }

              stack.splice(
                stack.length - bc[ip + 2],
                bc[ip + 2],
                peg$consts[bc[ip + 1]].apply(null, params)
              );

              ip += 4 + bc[ip + 3];
              break;

            case 27:
              stack.push(peg$parseRule(bc[ip + 1]));
              ip += 2;
              break;

            case 28:
              peg$silentFails++;
              ip++;
              break;

            case 29:
              peg$silentFails--;
              ip++;
              break;

            default:
              throw new Error("Invalid opcode: " + bc[ip] + ".");
          }
        }

        if (ends.length > 0) {
          end = ends.pop();
          ip = ips.pop();
        } else {
          break;
        }
      }

      return stack[0];
    }

    peg$result = peg$parseRule(peg$startRuleIndex);

    if (peg$result !== peg$FAILED && peg$currPos === input.length) {
      return peg$result;
    } else {
      if (peg$result !== peg$FAILED && peg$currPos < input.length) {
        peg$fail(peg$endExpectation());
      }

      throw peg$buildStructuredError(
        peg$maxFailExpected,
        peg$maxFailPos < input.length ? input.charAt(peg$maxFailPos) : null,
        peg$maxFailPos < input.length
          ? peg$computeLocation(peg$maxFailPos, peg$maxFailPos + 1)
          : peg$computeLocation(peg$maxFailPos, peg$maxFailPos)
      );
    }
  }

  return {
    SyntaxError: peg$SyntaxError,
    parse:       peg$parse
  };
})();
